/* tslint:disable */
/* eslint-disable */
/**
 * Currency Converter API
 * A simple REST API built with Kotlin and Spring Boot that provides currency conversion rates.  ## Features - Get conversion rates for a specific base currency - Returns rates in the format: `{currencycode: {inr: 1, cny: 2, etc}}` - Support for major currencies (USD, EUR, GBP, INR, JPY, CNY, CAD, AUD, CHF, SGD, KRW) - Health check endpoint - List supported currencies  ## Note This API uses mock exchange rates for demonstration purposes. In a production environment,  you would integrate with a real currency exchange rate API like Fixer.io, CurrencyLayer, or similar services. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
    /**
     * Error type
     * @type {string}
     * @memberof ErrorResponse
     */
    'error': string;
    /**
     * Detailed error message
     * @type {string}
     * @memberof ErrorResponse
     */
    'message': string;
    /**
     * List of supported currency codes (present in currency-related errors)
     * @type {Array<string>}
     * @memberof ErrorResponse
     */
    'supportedCurrencies'?: Array<string>;
}
/**
 * 
 * @export
 * @interface HealthResponse
 */
export interface HealthResponse {
    /**
     * Health status of the service
     * @type {string}
     * @memberof HealthResponse
     */
    'status': HealthResponseStatusEnum;
    /**
     * Name of the service
     * @type {string}
     * @memberof HealthResponse
     */
    'service': string;
}

export const HealthResponseStatusEnum = {
    Up: 'UP',
    Down: 'DOWN'
} as const;

export type HealthResponseStatusEnum = typeof HealthResponseStatusEnum[keyof typeof HealthResponseStatusEnum];

/**
 * 
 * @export
 * @interface SupportedCurrenciesResponse
 */
export interface SupportedCurrenciesResponse {
    /**
     * List of supported currency codes in lowercase
     * @type {Array<string>}
     * @memberof SupportedCurrenciesResponse
     */
    'supportedCurrencies': Array<string>;
    /**
     * Total number of supported currencies
     * @type {number}
     * @memberof SupportedCurrenciesResponse
     */
    'count': number;
}

/**
 * CurrencyConversionApi - axios parameter creator
 * @export
 */
export const CurrencyConversionApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves conversion rates for a specific base currency. Returns exchange rates  from the base currency to all other supported currencies. 
         * @summary Get currency conversion rates
         * @param {string} currencyCode The base currency code (case-insensitive)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrencyRates: async (currencyCode: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'currencyCode' is not null or undefined
            assertParamExists('getCurrencyRates', 'currencyCode', currencyCode)
            const localVarPath = `/api/{currencyCode}`
                .replace(`{${"currencyCode"}}`, encodeURIComponent(String(currencyCode)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CurrencyConversionApi - functional programming interface
 * @export
 */
export const CurrencyConversionApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CurrencyConversionApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieves conversion rates for a specific base currency. Returns exchange rates  from the base currency to all other supported currencies. 
         * @summary Get currency conversion rates
         * @param {string} currencyCode The base currency code (case-insensitive)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCurrencyRates(currencyCode: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: { [key: string]: number; }; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCurrencyRates(currencyCode, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CurrencyConversionApi.getCurrencyRates']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CurrencyConversionApi - factory interface
 * @export
 */
export const CurrencyConversionApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CurrencyConversionApiFp(configuration)
    return {
        /**
         * Retrieves conversion rates for a specific base currency. Returns exchange rates  from the base currency to all other supported currencies. 
         * @summary Get currency conversion rates
         * @param {string} currencyCode The base currency code (case-insensitive)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrencyRates(currencyCode: string, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: { [key: string]: number; }; }> {
            return localVarFp.getCurrencyRates(currencyCode, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CurrencyConversionApi - object-oriented interface
 * @export
 * @class CurrencyConversionApi
 * @extends {BaseAPI}
 */
export class CurrencyConversionApi extends BaseAPI {
    /**
     * Retrieves conversion rates for a specific base currency. Returns exchange rates  from the base currency to all other supported currencies. 
     * @summary Get currency conversion rates
     * @param {string} currencyCode The base currency code (case-insensitive)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CurrencyConversionApi
     */
    public getCurrencyRates(currencyCode: string, options?: RawAxiosRequestConfig) {
        return CurrencyConversionApiFp(this.configuration).getCurrencyRates(currencyCode, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * CurrencyInformationApi - axios parameter creator
 * @export
 */
export const CurrencyInformationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns a list of all supported currency codes along with the count
         * @summary Get supported currencies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSupportedCurrencies: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/currencies`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CurrencyInformationApi - functional programming interface
 * @export
 */
export const CurrencyInformationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CurrencyInformationApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns a list of all supported currency codes along with the count
         * @summary Get supported currencies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSupportedCurrencies(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SupportedCurrenciesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSupportedCurrencies(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CurrencyInformationApi.getSupportedCurrencies']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CurrencyInformationApi - factory interface
 * @export
 */
export const CurrencyInformationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CurrencyInformationApiFp(configuration)
    return {
        /**
         * Returns a list of all supported currency codes along with the count
         * @summary Get supported currencies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSupportedCurrencies(options?: RawAxiosRequestConfig): AxiosPromise<SupportedCurrenciesResponse> {
            return localVarFp.getSupportedCurrencies(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CurrencyInformationApi - object-oriented interface
 * @export
 * @class CurrencyInformationApi
 * @extends {BaseAPI}
 */
export class CurrencyInformationApi extends BaseAPI {
    /**
     * Returns a list of all supported currency codes along with the count
     * @summary Get supported currencies
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CurrencyInformationApi
     */
    public getSupportedCurrencies(options?: RawAxiosRequestConfig) {
        return CurrencyInformationApiFp(this.configuration).getSupportedCurrencies(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * HealthCheckApi - axios parameter creator
 * @export
 */
export const HealthCheckApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns the health status of the API service
         * @summary Health check endpoint
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheck: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HealthCheckApi - functional programming interface
 * @export
 */
export const HealthCheckApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HealthCheckApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns the health status of the API service
         * @summary Health check endpoint
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthCheck(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HealthResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthCheck(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HealthCheckApi.healthCheck']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HealthCheckApi - factory interface
 * @export
 */
export const HealthCheckApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HealthCheckApiFp(configuration)
    return {
        /**
         * Returns the health status of the API service
         * @summary Health check endpoint
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheck(options?: RawAxiosRequestConfig): AxiosPromise<HealthResponse> {
            return localVarFp.healthCheck(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HealthCheckApi - object-oriented interface
 * @export
 * @class HealthCheckApi
 * @extends {BaseAPI}
 */
export class HealthCheckApi extends BaseAPI {
    /**
     * Returns the health status of the API service
     * @summary Health check endpoint
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HealthCheckApi
     */
    public healthCheck(options?: RawAxiosRequestConfig) {
        return HealthCheckApiFp(this.configuration).healthCheck(options).then((request) => request(this.axios, this.basePath));
    }
}



