/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.currency.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.example.currency.client.apis.CurrencyInformationApi
import com.example.currency.client.models.SupportedCurrenciesResponse

class CurrencyInformationApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CurrencyInformationApi
        //val apiInstance = CurrencyInformationApi()

        // to test getSupportedCurrencies
        should("test getSupportedCurrencies") {
            // uncomment below to test getSupportedCurrencies
            //val result : SupportedCurrenciesResponse = apiInstance.getSupportedCurrencies()
            //result shouldBe ("TODO")
        }

    }
}
