/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.currency.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.example.currency.client.apis.CurrencyConversionApi
import com.example.currency.client.models.ErrorResponse

class CurrencyConversionApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CurrencyConversionApi
        //val apiInstance = CurrencyConversionApi()

        // to test getCurrencyRates
        should("test getCurrencyRates") {
            // uncomment below to test getCurrencyRates
            //val currencyCode : kotlin.String = usd // kotlin.String | The base currency code (case-insensitive)
            //val result : kotlin.collections.Map<kotlin.String, kotlin.collections.Map<kotlin.String, kotlin.Double>> = apiInstance.getCurrencyRates(currencyCode)
            //result shouldBe ("TODO")
        }

    }
}
