/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.currency.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.example.currency.client.apis.HealthCheckApi
import com.example.currency.client.models.HealthResponse

class HealthCheckApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of HealthCheckApi
        //val apiInstance = HealthCheckApi()

        // to test healthCheck
        should("test healthCheck") {
            // uncomment below to test healthCheck
            //val result : HealthResponse = apiInstance.healthCheck()
            //result shouldBe ("TODO")
        }

    }
}
