/**
 * Currency Converter API
 * A simple REST API built with Kotlin and Spring Boot that provides currency conversion rates.  ## Features - Get conversion rates for a specific base currency - Returns rates in the format: `{currencycode: {inr: 1, cny: 2, etc}}` - Support for major currencies (USD, EUR, GBP, INR, JPY, CNY, CAD, AUD, CHF, SGD, KRW) - Health check endpoint - List supported currencies  ## Note This API uses mock exchange rates for demonstration purposes. In a production environment, you would integrate with a real currency exchange rate API like Fixer.io, CurrencyLayer, or similar services.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.api

import org.openapitools.client.model.HealthResponse
import org.openapitools.client.core._
import org.openapitools.client.core.CollectionFormats._
import org.openapitools.client.core.ApiKeyLocations._

object HealthCheckApi {

  def apply(baseUrl: String = "http://localhost:8080") = new HealthCheckApi(baseUrl)
}

class HealthCheckApi(baseUrl: String) {

  /**
   * Returns the health status of the API service
   * 
   * Expected answers:
   *   code 200 : HealthResponse (Service is healthy)
   */
  def healthCheck(): ApiRequest[HealthResponse] =
    ApiRequest[HealthResponse](ApiMethods.GET, baseUrl, "/api/health", "application/json")
      .withSuccessResponse[HealthResponse](200)
      



}

