/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.currency.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param error Error type
 * @param message Detailed error message
 * @param supportedCurrencies List of supported currency codes (present in currency-related errors)
 */


data class ErrorResponse (

    /* Error type */
    @Json(name = "error")
    val error: kotlin.String,

    /* Detailed error message */
    @Json(name = "message")
    val message: kotlin.String,

    /* List of supported currency codes (present in currency-related errors) */
    @Json(name = "supportedCurrencies")
    val supportedCurrencies: kotlin.collections.List<kotlin.String>? = null

) {


}

