/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.currency.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param status Health status of the service
 * @param service Name of the service
 */


data class HealthResponse (

    /* Health status of the service */
    @Json(name = "status")
    val status: HealthResponse.Status,

    /* Name of the service */
    @Json(name = "service")
    val service: kotlin.String

) {

    /**
     * Health status of the service
     *
     * Values: UP,DOWN
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "UP") UP("UP"),
        @Json(name = "DOWN") DOWN("DOWN");
    }

}

