/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.currency.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param supportedCurrencies List of supported currency codes in lowercase
 * @param count Total number of supported currencies
 */


data class SupportedCurrenciesResponse (

    /* List of supported currency codes in lowercase */
    @Json(name = "supportedCurrencies")
    val supportedCurrencies: kotlin.collections.List<kotlin.String>,

    /* Total number of supported currencies */
    @Json(name = "count")
    val count: kotlin.Int

) {


}

