/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.currency.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.example.currency.client.models.ErrorResponse

class ErrorResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ErrorResponse
        //val modelInstance = ErrorResponse()

        // to test the property `error` - Error type
        should("test error") {
            // uncomment below to test the property
            //modelInstance.error shouldBe ("TODO")
        }

        // to test the property `message` - Detailed error message
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

        // to test the property `supportedCurrencies` - List of supported currency codes (present in currency-related errors)
        should("test supportedCurrencies") {
            // uncomment below to test the property
            //modelInstance.supportedCurrencies shouldBe ("TODO")
        }

    }
}
