/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.currency.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.example.currency.client.models.HealthResponse

class HealthResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of HealthResponse
        //val modelInstance = HealthResponse()

        // to test the property `status` - Health status of the service
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `service` - Name of the service
        should("test service") {
            // uncomment below to test the property
            //modelInstance.service shouldBe ("TODO")
        }

    }
}
