/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.currency.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.example.currency.client.models.SupportedCurrenciesResponse

class SupportedCurrenciesResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SupportedCurrenciesResponse
        //val modelInstance = SupportedCurrenciesResponse()

        // to test the property `supportedCurrencies` - List of supported currency codes in lowercase
        should("test supportedCurrencies") {
            // uncomment below to test the property
            //modelInstance.supportedCurrencies shouldBe ("TODO")
        }

        // to test the property `count` - Total number of supported currencies
        should("test count") {
            // uncomment below to test the property
            //modelInstance.count shouldBe ("TODO")
        }

    }
}
